### ISSUE TITLE
[M0 - Dev] Aclaración sobre las películas

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#10]
Buenas @pablo1mc315 abro este issue para saber sobre tu idea actual sobre las películas. La impresión que me ha dado, es que las películas tienen diferentes atributos:  
* Actores
* Año de estreno
* Género
* Lista de usuarios que la han visto

¿Sobran o faltan atributos?  
También pienso que el último atributo podría eliminarse e incluirse en la clase usuario, es decir, el usuario es el que tiene la lista de películas que ha visto. Dime tu opinión y avanzamos.

**Comment by pablo1mc315** [comment]
Buenas @pedromarting3. Sí, yo guardaría las películas con diferentes atributos y, a partir de ellos, realizar las distintas recomendaciones conforme a #12. Yo pondría estos atributos:

* Título
* Año de estreno
* Pequeña descripción (no se como lo ves, no es muy útil a efectos de la lógica de negocio, pero ayudaría al usuario a decidir entre una película o otra, pero no se hasta que punto estas cosas hay que ponerlas o no)
* Género
* Actores (lista)

En cuanto a la lista de usuarios que han visto una película, ¿no crees que es mejor al revés? Me refiero, si nuestra aplicación la utilizasen miles de usuarios, cada película sería vista por muchos usuarios. Sin embargo, si cada usuario ve x películas, sean muchas o pocas, serán muchas menos, y simplemente habría guardar cada una en una 'lista' y así ocupar menos espacio.

Dime que opinas sobre la descripción de las películas y, si se te ocurre algo más que se pudiese añadir, me vas diciendo 💪🏼

**Comment by pedrooot** [comment]
Me parece bien, la pequeña descripción será muy útil.

**Comment by pedrooot** [comment]
Buenas Pablo, estaba pensando y creo que es mucho mejor añadir algún ID a la película para poder identificarla mejor. A la hora de añadir una peli a la lista de vistas de un usuario, se simplificaría el proceso. Ya me dices que opinas al respecto!!

**Comment by pablo1mc315** [comment]
Me parece buena idea, si se me ocurre algún otro atributo más que pueda ser útil o necesario te comento

**Comment by pedrooot** [comment]
Se debe permitir añadir una película con la fecha de lanzamiento actual.
