### ISSUE TITLE
[M0 - Dev] Aclaración sobre los usuarios

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#11]
Hola @pablo1mc315 quiero consultarte un poco sobre tu idea de los usuarios:  
* ¿Usuario tiene ID?
* ¿Un usuario tiene 1 o varios géneros favoritos?
* ¿Un usuario tiene una lista de películas vistas?

Respecto al último ítem de la lista, lo he tratado también en el issue #10  
Cuando puedas me comentas, ya me dices!!

**Comment by pedrooot** [comment]
Otra pregunta:  
* ¿Usuario tiene x actores favoritos?

**Comment by pablo1mc315** [comment]
En cuanto a lo de guardar las películas vistas, creo que es mejor guardarlo en los atributos del usuario, como te he comentado en #10.

Por otro lado, creo que estaría bien que cada usuario tuviese una ID para distinguirlos, ya que, creo que es lo más correcto, aunque también es cierto que los nombres de usuario o correos también pueden ser únicos para cada uno, entonces no sé si es del todo necesario. ¿Qué opinas tú?

En cuanto a los géneros favoritos, yo diría que lo correcto es que pueda tener varios, ya que la mayoría de personas no ven películas de un único género.

Los actores, yo tenía la idea de hacerlo, no por actores favoritos como tal, sino por actores que participan en cada película. Así, si tu ves una película en la que aparece un actor, ya se puede usar eso para el sistema de recomendaciones. Por ello no creo que sea necesario que cada usuario tenga actores favoritos, lo cual complicaría más la aplicación de manera innecesaria.

**Comment by pedrooot** [comment]
Creo que la mejor opción es identificar a cada usuario con su correo electrónico.  

Concuerdo contigo en el resto! 😬

**Comment by pablo1mc315** [comment]
Perfecto, pues lo hacemos mediante el correo electronico sin problema!

**Comment by pablo1mc315** [comment]
@pedromarting3 según acaba de decir el profesor en clase, ¿crees que haría falta un histórico de las películas vistas? lo digo porque, en ese caso, habría que añadir también la fecha en la que se ha visto esa película, pero te pregunto por saber si lo habías tenido en cuenta

**Comment by pedrooot** [comment]
Así es Pablo, creo que podríamos encontrar la forma de relacionar la película con la fecha vista. En la lista de películas vistas (del usuario), se podría relacionar cada ID con la fecha en la que se ve la película.

**Comment by pablo1mc315** [comment]
A eso me refiero, de alguna manera almacenar la 'lista de películas vistas' como parejas de valores ID/fecha. Pero también te digo, no se hasta que punto eso es útil o necesario para hacer las recomendaciones
