### ISSUE TITLE
[M0 - Dev] Aclaración sobre el algoritmo de recomendación de películas

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#12]
@pablo1mc315 abro este issue para planificar la implementación sobre la forma en la que se van a recomendar las películas a los usuarios. ¿Qué criterio se usa para recomendar una película a un usuario? Había pensado recomendar una película a un usuario si:    
* No la ha visto
* El género de la película es un género que le gusta al usuario
* ¿Añadir "puntuaciones" a las películas para así poder recomendarlas mejor?  

Este último check modificaría el issue #10 añadiéndole un nuevo atributo a las películas. Cuando puedas me dices.

**Comment by pedrooot** [comment]
Me ha faltado añadir que el algoritmo también consideraría los actores que participan en la película.

**Comment by pablo1mc315** [comment]
Que el algoritmo considere los actores que participan en la película y los compare con los actores de la lista de películas "vistas" del usuario me parece un buen punto para una recomendación. También es factible hacerlo de la misma forma según el género de esa lista de películas o el género favorito del usuario.

El sistema de puntuaciones no es algo que afecte directamente a la lógica de negocio como tal, entonces pienso que es algo que puede complicar la aplicación demasiado (no se como de complicado puede ser implementarlo ni cuanto tiempo puede conllevar) pero lo podemos dejar como algo "posible" e implementarlo si diese tiempo.

El hecho de que un usuario no haya visto la película pienso que debería darle peso respecto a las otras. Por ejemplo, si dos películas cumplen los mismos requisitos en cuanto a recomendación (género, actores, etc.) y una de ellas no se ha visto, que se muestre esa por delante de la otra en la lista de recomendadas. Dime que opinas o si crees que se podría añadir algún factor más y vamos hablándolo.

**Comment by pedrooot** [comment]
De lujo, lo más importante al realizar una búsqueda es que un usuario no haya visto la película y a partir de ahí seguimos con el géneros y actores.  
Me pongo manos a la obra👨🏻‍💻

**Comment by pablo1mc315** [comment]
Dale a eso!! 💪🏼
