### ISSUE TITLE
[M0 - Dev] Proposición sobre estructura de datos

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#13]
## [Clase User](#11 )
* [x] ID de usuario (correo electrónico).
* [x] Lista de géneros favoritos.
* [x] Lista de películas vistas con fecha en las que las ve.
## [Clase Film](#10 )
* [x] La película tiene título.
* [x] La película tiene ID (con el que se identificará la película).
* [x] Fecha de lanzamiento de la película (año).
* [x] Pequeña descripción de la película.
* [x] Género de la película.
* [x] Actores que aparecen.  
## Clase UserCollection
* [x] Colección de usuarios
## Clase FilmCollection
* [x] Colección de películas
## Clase Suggestions
* [x] Contiene una colección de películas recomendadas para cada usuario

## Explicación  
Buenas @pablo1mc315 , he creado esta lista para ir marcando los checks cuando vaya implementando esta estructura. Cuando me digas si te parece bien comienzo con la implementación de las clases!!🏌🏽‍♂️

**Comment by pablo1mc315** [comment]
Lo veo todo correcto, ya te digo si se me ocurre algo más te comento, pero de momento lo veo perfecto! 💪🏼

**Comment by pablo1mc315** [comment]
@pedromarting3 no se te olvide añadir aquí los datos de las otras clases que acordamos (la de las colecciones y la de la implementacion de la lógica de negocio) 😉

**Comment by pedrooot** [comment]
Ya he actualizado esto @pablo1mc315

**Comment by pablo1mc315** [comment]
Perfecto! 👍🏻

**Comment by pedrooot** [comment]
@pablo1mc315 Ya he hecho todos los esqueletos de clases por lo que creo que la estructura de datos ha avanzado bastante. Dime que opinas cuando puedas 😺

**Comment by pablo1mc315** [comment]
Yo la veo bastante bien, parece que esta todo lo que hemos hablado así que por mi parte perfecto!!

Una duda, en los usuarios, ¿la lista de peliculas vistas con la fecha en la q se vio, se implementa como un array o hay otra forma de implementarlo en node? (Algo como una lista de pares o algo así, que no se si lo has tenido en cuenta o si se hace como lo has hecho)

PD: no se si es una errata pero en las pelis has puesto tittle con dos t, es una tontería pero por ponerte alguna pega 😂  😉

**Comment by pedrooot** [comment]
Tienes razón, debo de modificar la clase user para añadir lo de las fechas. Se me había pasado😮‍💨

**Comment by pedrooot** [comment]
Esta noche me quedaré hasta tarde, mañana debería de estar listo.

**Comment by pedrooot** [comment]
Pues he encontrado un hueco y ha sido menos costoso de lo que esperaba, échale un viztazo @pablo1mc315 🤑

**Comment by pedrooot** [comment]
No lo apruebes todavía que mañana a las 8:30 tengo clase de prácticas de IV y quiero preguntarle cosillas a Juan. Seguimos en contacto.

**Comment by pedrooot** [comment]
Esto hay que darle una vuelta, la estructura de clases es incorrecta. Hay que tener en cuenta:  
* Conjuntos son innecesarios, necesitamos diccionario con pares de valores. La mejor idea es la implementación de la clase "películas vistas" en la que se guarda una coleccion de claves pares. [usuario] ->[ película vista con fecha y veces que la ha visto]

**Comment by pablo1mc315** [comment]
Me parece buena solución, en esa clase puedes crear un atributo de tipo usuario, otro de tipo película y otro de tipo fecha y así tener toda la información. Las veces que la ha visto, como te digo en #17 creo que no es necesario pues con saber si la ha visto una vez es suficiente.

**Comment by pedrooot** [comment]
Así me queda mas claro. Te abro un issue para comentar lo de la fecha.

**Comment by pedrooot** [comment]
Buenas Pablo, al principio propusimos la estructura de film con el atributo description pero no hay ninguna historia de usuario que lo apoye. Pienso que lo correcto sería eliminarlo, ¿qué piensas al respecto?

**Comment by pablo1mc315** [comment]
Ya lo hablamos por aquí, pero en resumen no afecta a ninguna HU así que puedes eliminarlo
