### ISSUE TITLE
[M0 - Dev] Proposición errónea sobre la estructura de clases 

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#14]
Hoola @pablo1mc315 tras comentarle nuestra idea al profesor, me ha ayudado a darme cuenta de un error bastante gordo. Estamos tratando la clase usuario y la clase películas como entidades separadas que no implementan la lógica de negocio. Necesitamos una clase que la implemente relacionando ambas estructuras.  

Actualmente estoy un poco en blanco pero se me ha ocurrido que podríamos crear una clase "FilmCollection" que sería un conjunto de películas. Al igual que podríamos crear otra clase "UserCollection" que albergará el conjunto de usuarios.  

Desde este punto, no sabría cómo implementar la lógica de negocio pero al menos, ya tenemos una relacion de muchos (usuarios) a muchos (películas).  

Cuando puedas me dices qué opinas al respecto y a ver si se te ocurre a ti algo.

**Comment by pedrooot** [comment]
🧙🏿‍♂️

**Comment by pablo1mc315** [comment]
Las clases FilmCollection y UserCollection son las que se corresponden con las clases Usuario y Pelicula? Y faltaría una clase intermedia para la implementación de la lógica de negocio??

**Comment by pedrooot** [comment]
No, estas clases son las que agrupan a las instancias individuales de las otras.  
En total tendríamos:  
* Clase Usuario
* Clase Película
* Clase UserCollection
* Clase FilmCollection
* CLASE LOGICA NEGOCIO

**Comment by pablo1mc315** [comment]
Ah vale vale,perfecto entonces

**Comment by pablo1mc315** [comment]
Vale, creo q he entendido el concepto y te propongo algo: que tal si en las clases UserCollection y FilmCollection añades un atributo en cada una que sea una coleccion (lista o cualquier otro tipo que creas conveniente) de objetos de la clase Usuario y Pelicula, respectivamente. Así ya tenemos almacenadas las colecciones de peliculas de cada usuario y en la clase "logica de negocio" crear un objeto de cada tipo q se pueda inicializar a la lista de peliculas de cada usurio y de la propia aplicacion para ahi hacer las recomendaciones. ¿Me explico?

Por cierto, es una tonteria pero ¿te parece si llamamos a las clases Usuario y Pelicula: User y Flim, respectivamente? Mas que nada para que sea todo igual y mas intuitivo :)

**Comment by pablo1mc315** [comment]
Por cierto, es una tonteria pero ¿te parece si llamamos a las clases Usuario y Pelicula: User y Flim, respectivamente? Mas que nada para que sea todo igual y mas intuitivo :)

**Comment by pedrooot** [comment]
Perfecto, te entiendo @pablo1mc315  

Lo hacemos así, la estructura de clases quedaría así:  

* Clase User 
* Clase Film
* Clase UserCollection (contiene el conjunto de usuarios)
* Clase FilmCollection (contiene el conjunto de películas)
* Clase Suggestions (permite hacer las recomendaciones)

Creo que quedaría así, no crees?

**Comment by pablo1mc315** [comment]
Si @pedromarting3 me parece bastante bien! Dale a eso 💪🏼
