### ISSUE TITLE
[M0 - Dev] Aclaración sobre historias de usuario

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#15]
Buenas @pablo1mc315 , he visto que las historias de usuario están asignadas al m3 cuando deberíamos de empezar con el m0.  

Modificamos eso o que hacemos?

**Comment by pedrooot** [comment]
Es que ambas historias están relacionadas con la búsqueda de películas. Poco mas.

**Comment by pablo1mc315** [comment]
Sí, es que ambas HU se refieren a las necesidades del usuario, que en este caso es el sistema de recomendaciones. JJ no me dijo nada al respecto y no se exactamente que HU se puede referir al M0, pues las HU son necesidades del usuario y creo que no hay ninguna que se pueda relacionar con el M0. No sé que opinas tú.
