### ISSUE TITLE
[M0 - Dev] Que hace falta modelizar en el modelo de usuario

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#16]
Que se necesita del usuario para que se pueda implementar la lógica de negocio y use un objeto mínimamente viable.

**Comment by pablo1mc315** [comment]
Básicamente del usuario necesitamos los géneros de las películas que suele "buscar" en la aplicación, sus géneros favoritos y las películas que ha visto, para implementar la lógica de negocio (en este caso, un sistema de recomendaciones que se adecúe a los gustos del usuario).
