### ISSUE TITLE
[M0 - Dev] Implementación de la búsqueda

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#17]
@pablo1mc315 tengo varias dudas sobre la búsqueda:  
* ¿La búsqueda tiene en cuenta las veces que se ha visto de una película?
* ¿La búsqueda se puede hacer a partir de varios géneros?
* ¿La búsqueda se puede hacer a partir de varios actores?

**Comment by pablo1mc315** [comment]
Creo que te refieres al concepto de "recomendaciones". La búsqueda se basa simplemente en un apartado de la aplicación que permite al usuario buscar una película por su título o género, lo cual nos ayudará a obtener datos de los gustos del usuario para hacer las recomendaciones. En cuanto a estas:

- Creo que no tiene que tener en cuenta si se ha visto una o varias veces, simplemente marcar si una película ha sido vista o no y mostrar con prioridad mayor las que no se han visto como ya comentamos en otro issue.
- Sí, estaría bien que la recomendación se hiciese en cuanto a los géneros favoritos del usuario (que ya tenemos guardados como atributo) y, estos géneros, se pueden obtener mediante las películas vistas y mediante las búsquedas que suele realizar.
- Como te comento en #18 , no se que hacer con el tema de los actores. Si quieres esto lo seguimos discutiendo en ese issue para no mezclar la conversación.

Cualquier duda me dices y lo comentamos !!
