### ISSUE TITLE
[M0 - Dev] Obtención de los datos

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#18]
Buenas @pablo1mc315 estoy pensando esto un poco y quiero saber si has encontrado un dataset o algo así para obtener los datos de las películas. Inicialmente necesito verificar:  
* Los géneros de las películas.
* Los actores que aparecen.
* El año de lanzamiento.

Todos estos datos no pueden ser introducidos por el usuario ya que nuestro servicio debe permitir añadir películas con atributos correctos (P.Ej: no se puede poner un año de lanzamiento negativo [-2001])

**Comment by pablo1mc315** [comment]
En cuanto al dataset, había pensado en el de IMDb que se puede descargar [aquí](https://www.imdb.com/interfaces/), concretamente el que tiene el nombre de 'title.basics.tsv.gz'. Esto descarga un fichero .tsv que contiene información sobre el título, si es para adultos o no, el año de lanzamiento, el año de finalización (si es una serie, si es una película es nulo), la duración y los géneros a los que pertenece. En cuanto a los actores no sé exactamente que hacer, ya que no he encontrado ninguna BBDD que diga cuáles aparecen en cada serie, así que no sé si es mejor quitarlos y no hacer recomendaciones en cuanto a actores, pero claro, eso ya me afecta en cuanto a #5. ¿Tú que opinas?

**Comment by pablo1mc315** [comment]
Vale, he estado mirando y en la página que te he mencionado hay un fichero 'title.principals.tsv.gz' que guarda los actores que hay en cada película. Creo que las ID de las películas son las mismas de un fichero a otro, por lo que siendo así bastaría con buscar por ID de la película en este fichero para encontrar qué actores aparecen. Le echo un ojo y te comento

**Comment by pedrooot** [comment]
Perfecto ya me dices 🙌🏽
