### ISSUE TITLE
[M0 - Dev] Formato de las fechas

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#20]
Buenas @pablo1mc315 tengo una duda sobre las fechas. ¿Cuál es la precisión que debe tener? A lo que me refiero es que no sé si es suficiente que tenga año o si es necesario que tenga el formato día/mes/año. (Yo opto por esta última opción)

**Comment by pablo1mc315** [comment]
A ver, teniendo en cuenta que las fechas solo se van a referir a las películas, creo que bastaría con el año solo, ya que no creo que haya dos películas que se llamen igual que hayan saludo en el mismo año. Mi idea de poner la fecha de lanzamiento era para distinguir dos películas con el mismo nombre (que se hayan remasterizado o cualquier cosa). ¿Qué opinas?

**Comment by pedrooot** [comment]
De lujo, con el año se justifica bien
