### ISSUE TITLE
[M0 - Dev] Idioma usado para los géneros/implementación general

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#21]
Buenas @pablo1mc315 tras la propuesta de cambios de juan considero que es necesario determinar el lenguaje que vamos a usar a la hora de implementar el objetivo 2. ¿Piensas que habría que cambiar el idioma de todo o se podría seguir implementando en inglés?

**Comment by pablo1mc315** [comment]
Yo no tengo problema en hacerlo en inglés, como ya los nombres de las clases los pusimos en ingles pues por no mezclar, pero no veo necesario cambiarlo todo al español. ¿Tu que opinas?

**Comment by pedrooot** [comment]
Lo dejamos en inglés ya que lo tenemos, que se note que somos bilingües 😂

**Comment by pedrooot** [comment]
Según la historia de usuario, los géneros están en castellano
