### ISSUE TITLE
[M0 - Dev] Formato errores

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#22]
Buenas @pablo1mc315, ¿será necesario manejar los errores en el caso de que se introduzcan valores erróneos en los datos? Esta funcionalidad pienso que es bastante útil pero realmente no está en ningún issue/milestone.

**Comment by pablo1mc315** [comment]
Yo también la veo útil, pero no está en ninguna HU ya que no creo q sea algo que directamente afecte al usuario, pero sí, veo bastante útil su implementación

**Comment by pedrooot** [comment]
Perfecto!!
