### ISSUE TITLE
[M0 - Dev] Equivocación de objeto valor

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#23]
Buenas @pablo1mc315 estamos tomando la película como objeto valor pero en la implementación he creado métodos para que estas sean mutables (se puede cambiar el nombre...) pero no es correcto porque un objeto valor es inmutable. Pienso que eliminando los métodos que he creado de forma incorrecta se solucionaría. ¿Qué opinas?

**Comment by pablo1mc315** [comment]
La pregunta es, ¿por qué deberían modificarse los datos? Por ejemplo, ¿para que querríamos modificar el nombre o la fecha de lanzamiento de una película una vez que ya se haya creado? Yo veo correcto que los elimines, dale una vuelta a todos y si quieres planteamos cuales son útiles y cuales no, pero yo creo que casi todos por no decir todos los setters sobrarían. Dale una vuelta y me dices

**Comment by pedrooot** [comment]
Razón no te falta, estoy de acuerdo contigo.

**Comment by pedrooot** [comment]
De hecho, es inútil añadir por ejemplo, un género nuevo a una película

**Comment by pedrooot** [comment]
No se cómo estaba en ese momento para hacer esto, lo soluciono rápido.

**Comment by pedrooot** [comment]
Buenas, estoy pensando la modificación de la clase y sería necesario comprobar que los datos introducidos en el constructor sean válidos (por ejemplo, que un actor o un género no se haya introducido ya...) ¿Te parece bien si la comprobación está en el constructor?

**Comment by pedrooot** [comment]
@pablo1mc315

**Comment by pablo1mc315** [comment]
> No se cómo estaba en ese momento para hacer esto, lo soluciono rápido.

Sí, culpa mía que tampoco presté atención a ese detalle, pero mejor tarde que nunca JAJAJAJAJ

**Comment by pablo1mc315** [comment]
> Buenas, estoy pensando la modificación de la clase y sería necesario comprobar que los datos introducidos en el constructor sean válidos (por ejemplo, que un actor o un género no se haya introducido ya...) ¿Te parece bien si la comprobación está en el constructor?

No me parece mal, de hecho de otra forma habría que comprobarlos cada vez que se cree un objeto de ese tipo, así que mejor que estén las comprobaciones necesarias en el constructor. Lo que no estoy seguro es: si no cumple con lo necesario para crear el objeto, por ejemplo el género no es correcto, ¿qué se hace con el objeto? ya se estaría creando dentro del propio constructor, a no ser q se le asigne Null o algo así, que piensas?

**Comment by pedrooot** [comment]
En el momento que se quiera introducir un valor incorrecto a una película que lance un error para saberlo.

**Comment by pablo1mc315** [comment]
Vale, no sabía que existía esa posibilidad asi que me parece bien!
