### ISSUE TITLE
[M0 - Dev] Aclaración sobre validación y estructura de clases

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#24]
Buenas @pablo1mc315 te abro el issue para solucionar el problema que tenemos actualmente sobre la implementación. En este objetivo no es necesaria la validación de los datos que se van a introducir por lo que no veo necesaria la clase genresSet que utilizábamos para verificar que un género es válido. ¿Qué opinas al respecto?

**Comment by pablo1mc315** [comment]
Eso he visto en la corrección. Si no es necesario en este issue, elimínalo y ya está, sin problema
