### ISSUE TITLE
[M0 - Dev] Aclaración sobre usuario sin géneros favoritos ni películas vistas

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#25]
Buenas @pablo1mc315 tengo la siguiente duda:  
¿Se podría crear un usuario sin películas vistas y sin géneros favoritos?

**Comment by pablo1mc315** [comment]
Sí, diría que sí, ya que cuando un usuario entra la primera vez a la aplicación no tiene películas vistas ni géneros favoritos, eso se irá modificando conforme vaya interactuando con la aplicación.

**Comment by pedrooot** [comment]
Perfecto!🏌🏽‍♂️
