### ISSUE TITLE
[M1 - Dev] Es necesario comprobar que las bibliotecas se cargan correctamente

### ISSUE THREAD

**Issue by pablo1mc315** [pablo1mc315/iv_pablomc#40]
Para ello, vamos a formular tests que carguen las bibliotecas y comprueben que no hay error al realizar dicha tarea

**Comment by pablo1mc315** [comment]
Marcado como `invalid` tras la revisión del profesor. No son necesarios este tipo de tests.

**Comment by JJ** [comment]
Esto es algo obvio. No es un problema, ni debe ser un issue. La validez o no del código debe formar parte de un milestone y se debe comprobar automáticamente.
Adicionalmente, se ha creado código asignado a este issue que no tiene nada que ver ni con la formulación anterior ni con la actual. Os recuerdo que la forma correcta de proceder cuando se ha hecho código con un issue incorrecto no es editar el issue, sino borrar el código y desarrollar desde cero asignado a un nuevo issue.

**Comment by pablo1mc315** [comment]
Lo sé, por eso esta marcado como `invalid`, todos los cambios realizados que se corresponden con este issue fueron hechos antes de la primera revisión y, por tanto, modificados.
