### ISSUE TITLE
[M0 - Dev] Elección de lenguaje de programación

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#8]
Hola Pablo!!  
He creado este issue para comenzar con la implementación del objetivo 2 y preguntarte sobre qué leguaje te gustaría usar. Ten en cuenta las restricciones que tiene tu proyecto para determinar las características necesarias de tu lenguaje.  
Al lio! 🚀

**Comment by pablo1mc315** [comment]
Hola Pedro!! Perfecto, he pensado en hacerlo en node.js, ya que he estado investigando y creo que es el más adecuado para lo que requiere la asignatura, pero si tienes otra opinión dimelo y lo vemos.

**Comment by pedrooot** [comment]
Perfecto! Lo hacemos con Node.js, seguimos en contacto. 🫡
