### ISSUE TITLE
[M0 - Dev] Aclaración sobre lógica de negocio

### ISSUE THREAD

**Issue by pedrooot** [pablo1mc315/iv_pablomc#9]
Buenas Pablo, ¿me podrías explicar la lógica de negocio del servicio?

**Comment by pedrooot** [comment]
@pablo1mc315

**Comment by pablo1mc315** [comment]
Buenas, @pedromarting3. Principalmente, la lógica de negocio de mi aplicación se basa en crear un sistema de recomendaciones que funcione de manera correcta y que ofrezca al usuario las mejores películas en función de sus géneros o actores más consumidos/buscados.

**Comment by pedrooot** [comment]
Ahh vale, ya lo entiendo jeje

**Comment by pedrooot** [comment]
Hay que repasar esto

**Comment by pedrooot** [comment]
Pablo no entiendo bien la lógica de negocio, no sabría determinar cual es un producto mínimamente viable.

**Comment by pablo1mc315** [comment]
Según he visto en otros ISSUES y como te he comentado en #17, creo que estabas confundiendo o mezclando los conceptos de "búsqueda" y "recomendaciones", que son dos partes distintas de la app. Las recomendaciones es el objetivo de la lógica de negocio, mientras que la búsqueda es un apartado de la app que nos ayudará a obtener datos para realizar unas recomendaciones acordes a los gustos del usuario. ¿Te queda más claro?

**Comment by pedrooot** [comment]
Ahora sí. Muchas gracias jeje😺

**Comment by JJ** [comment]
Tampoco hay ningún commit que se refiera a este issue. Todos los issues deben resultar en cambios en el código.

**Comment by JJ** [comment]
No se cierra nunca desde el interfaz, o te dará error a partir de ahora siempre cada vez que subas un objetivo. Se cierra desde commit o PR.
